version: "3.8"
services:
  ubuntu_service:
    image: ubuntu
    deploy:
      replicas: 4
    command: tail -f /dev/null

  nginx_service:
    image: nginx
    container_name: my-container
    command: tail -f /dev/null
